/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundCancellationPolicyRouteImport } from './routes/refund-cancellation-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BootstrapAdminRouteImport } from './routes/bootstrap-admin'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhatsappInboxRouteImport } from './routes/api/whatsapp-inbox'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppSystemCheckRouteImport } from './routes/_app.system-check'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSignupsRouteImport } from './routes/_app.signups'
import { Route as AppRepsRouteImport } from './routes/_app.reps'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppLeadsNewRouteImport } from './routes/_app.leads_.new'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationPolicyRoute =
  RefundCancellationPolicyRouteImport.update({
    id: '/refund-cancellation-policy',
    path: '/refund-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapAdminRoute = BootstrapAdminRouteImport.update({
  id: '/bootstrap-admin',
  path: '/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappInboxRoute = ApiWhatsappInboxRouteImport.update({
  id: '/api/whatsapp-inbox',
  path: '/api/whatsapp-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemCheckRoute = AppSystemCheckRouteImport.update({
  id: '/system-check',
  path: '/system-check',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupsRoute = AppSignupsRouteImport.update({
  id: '/signups',
  path: '/signups',
  getParentRoute: () => AppRoute,
} as any)
const AppRepsRoute = AppRepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsNewRoute = AppLeadsNewRouteImport.update({
  id: '/leads_/new',
  path: '/leads/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-debug': typeof AuthDebugRoute
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/meetings': typeof AppMeetingsRoute
  '/performance': typeof AppPerformanceRoute
  '/reps': typeof AppRepsRoute
  '/signups': typeof AppSignupsRoute
  '/support': typeof AppSupportRoute
  '/system-check': typeof AppSystemCheckRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/whatsapp-inbox': typeof ApiWhatsappInboxRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/leads/new': typeof AppLeadsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-debug': typeof AuthDebugRoute
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/meetings': typeof AppMeetingsRoute
  '/performance': typeof AppPerformanceRoute
  '/reps': typeof AppRepsRoute
  '/signups': typeof AppSignupsRoute
  '/support': typeof AppSupportRoute
  '/system-check': typeof AppSystemCheckRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/whatsapp-inbox': typeof ApiWhatsappInboxRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/leads/new': typeof AppLeadsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/reps': typeof AppRepsRoute
  '/_app/signups': typeof AppSignupsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/system-check': typeof AppSystemCheckRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/whatsapp-inbox': typeof ApiWhatsappInboxRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/leads_/new': typeof AppLeadsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-debug'
    | '/bootstrap-admin'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/reset-password'
    | '/terms-and-conditions'
    | '/activity'
    | '/dashboard'
    | '/leads'
    | '/meetings'
    | '/performance'
    | '/reps'
    | '/signups'
    | '/support'
    | '/system-check'
    | '/whatsapp'
    | '/api/whatsapp'
    | '/api/whatsapp-inbox'
    | '/leads/$leadId'
    | '/leads/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-debug'
    | '/bootstrap-admin'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/reset-password'
    | '/terms-and-conditions'
    | '/activity'
    | '/dashboard'
    | '/leads'
    | '/meetings'
    | '/performance'
    | '/reps'
    | '/signups'
    | '/support'
    | '/system-check'
    | '/whatsapp'
    | '/api/whatsapp'
    | '/api/whatsapp-inbox'
    | '/leads/$leadId'
    | '/leads/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth-debug'
    | '/bootstrap-admin'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/reset-password'
    | '/terms-and-conditions'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/meetings'
    | '/_app/performance'
    | '/_app/reps'
    | '/_app/signups'
    | '/_app/support'
    | '/_app/system-check'
    | '/_app/whatsapp'
    | '/api/whatsapp'
    | '/api/whatsapp-inbox'
    | '/_app/leads/$leadId'
    | '/_app/leads_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthDebugRoute: typeof AuthDebugRoute
  BootstrapAdminRoute: typeof BootstrapAdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundCancellationPolicyRoute: typeof RefundCancellationPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  ApiWhatsappInboxRoute: typeof ApiWhatsappInboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation-policy': {
      id: '/refund-cancellation-policy'
      path: '/refund-cancellation-policy'
      fullPath: '/refund-cancellation-policy'
      preLoaderRoute: typeof RefundCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap-admin': {
      id: '/bootstrap-admin'
      path: '/bootstrap-admin'
      fullPath: '/bootstrap-admin'
      preLoaderRoute: typeof BootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-inbox': {
      id: '/api/whatsapp-inbox'
      path: '/api/whatsapp-inbox'
      fullPath: '/api/whatsapp-inbox'
      preLoaderRoute: typeof ApiWhatsappInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-check': {
      id: '/_app/system-check'
      path: '/system-check'
      fullPath: '/system-check'
      preLoaderRoute: typeof AppSystemCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signups': {
      id: '/_app/signups'
      path: '/signups'
      fullPath: '/signups'
      preLoaderRoute: typeof AppSignupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reps': {
      id: '/_app/reps'
      path: '/reps'
      fullPath: '/reps'
      preLoaderRoute: typeof AppRepsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads_/new': {
      id: '/_app/leads_/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof AppLeadsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppRepsRoute: typeof AppRepsRoute
  AppSignupsRoute: typeof AppSignupsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppSystemCheckRoute: typeof AppSystemCheckRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppLeadsNewRoute: typeof AppLeadsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMeetingsRoute: AppMeetingsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppRepsRoute: AppRepsRoute,
  AppSignupsRoute: AppSignupsRoute,
  AppSupportRoute: AppSupportRoute,
  AppSystemCheckRoute: AppSystemCheckRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppLeadsNewRoute: AppLeadsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthDebugRoute: AuthDebugRoute,
  BootstrapAdminRoute: BootstrapAdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundCancellationPolicyRoute: RefundCancellationPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  ApiWhatsappInboxRoute: ApiWhatsappInboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
